### ISSUE TITLE
Predictions in correlation menu not working properly after JAMOVI update

### ISSUE THREAD

**Issue by romina-gonzalez-musso** [rcalinjageman/esci#48]
Hi Robert and team!

First of all, congratulations for this great package! Very useful indeed! We writing from the Forestry School, National University of Comahue in Patagonia Argentina. We’ve using the Esci module for Jamovi quite a lot for teaching. 

Recently, after the last update of Jamovi (from 2.4.11 to 2.5.0), one of the functionalities of the module is not working. When trying to use the prediction option in the regression analysis (_Correlations → Single group_), we get a blank result and no intervals are shown in the scatterplot. A message in red says “_invalid value for 0 ‘digits argument_” (see first screenshot). This happens when entering a _X_ value to generate prediction (_Y_) when the intervals checkboxes are selected. If we enter the _X_ value without ticking the _Prediction Intervals_ or the _CI on line_ checkboxes, it seems to work but yet no intervals are provided.

![1](https://github.com/rcalinjageman/esci/assets/24296493/2af71cd8-27fd-41aa-95ff-3518139ae48d)

I ran a test in a computer that wasn't updated yet (Jamovi still in 2.4.11) and it works just fine:  

![Captura de pantalla de 2024-03-12 14-18-56](https://github.com/rcalinjageman/esci/assets/24296493/6f210fa3-dd40-45f2-ba01-e91a58c5cfb1)

We guess something is not working properly after this last Jamovi update. We are working in Linux machines (Linux Mint 21/Ubuntu 22.04). Jamovi is installed with Flatpak.  

Hope this post helps to solve the issue. 
Best,
Romina

**Comment by rcalinjageman** [comment]
I haven't had a chance to look into the 2.5 release yet -- but there have been some updates to underlying packages that could cause this type of problem.  I'll take a look and hopefully can push out an update soon (had just been prepping an update anyway, with data files and some other little tweaks).

If you notice any other broken behaviors with 2.5 let me know.

**Comment by romina-gonzalez-musso** [comment]
Hi Robert! This is the only problem we've found so far. 
 
This Jamovi release caught us right on the spot because we're about to give a training course on statistcs applied to forestry, and we're using the Esci module quite a lot. That's why we found this issue regarding predictions and intervals in the _Correlations_ module so quickly. I got distracted and updated all packages that were suggested in the Linux software manager including this new Jamovi version.

Hope this issue is easy to solve in the new update!

Best,
Romina

**Comment by rcalinjageman** [comment]
Romina,
I've found the issue, and it is an easy fix. I've applied the update to the esci package for R which lives here on github.  The only issue I have now is that the windows update to jamovi 2.5 isn't available yet, so I can't test the fix with jamovi just yet.  Working on it.

**Comment by rcalinjageman** [comment]
I've managed to get 2.5 for windows and test out the fixes.  Found an additional issue that was throwing an error in means/medians analyses when the grouping variable wasn't yet defined, and fixed that as well.  I've asked the jamovi team to push out the update, which will be to esci 1.0.2.  That might take a day or two.. not sure.  This 1.0.2 edition also adds data files to the module and references.

**Comment by romina-gonzalez-musso** [comment]
Great news! Good to know it was an easy fix. I'll keep an eye on the Esci update for Jamovi 2.5 and see how it goes.

**Comment by romina-gonzalez-musso** [comment]
Well, it was fast! Esci 1.0.2 is now available in Jamovi 2.5 and running smoothly. 

Nice work! Thanks!

**Comment by rcalinjageman** [comment]
Glad it worked out.  Any other feedback or feature requests welcome.  It is a great joy to know that esci is of use in your teaching.
