### ISSUE TITLE
2x2 plots sometimes select too-wide y-axis range

### ISSUE THREAD

**Issue by jwilmer** [rcalinjageman/esci#9]
Here is an example (https://www.dropbox.com/s/pdgg4paf3dufch4/example.omv?dl=1). 
The y-axis shows up for me as -200 to +250 even though the furthest extent of the downward end of the cat's eye is about -90. 
This is not the most extreme example, but it is what I had handy. 
Y-axis range also sometimes changes unpredictably when I paste in new columns of data that are not included in the present analysis. 
Maybe add a feature to allow the user to select their own y-axis range? 
(I assume that's easier than figuring out a priori what the best range is for all possible data sets)

**Comment by rcalinjageman** [comment]
Sorry for the long delay in addressing this issue.  I've now completely rewritten esci.  The R package is here on github; the jamovi module is available in the jamovi module library (esci 1.01; you need at least jamovi 2.4 to install it).  This updated version allows you to control the y axis limits on all graphs (and font size, color, etc.).  Let me know what you think!
